openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing contacts and user authentication.
tags:
  - name: Contacts
    description: Operations for creating, retrieving, updating, and deleting contacts.
  - name: Auth
    description: Operations for user registration, login, and authentication management.
servers:
  - url: http://localhost:3000
  # - url: https://nodejs-hw-mongodb-c3yu.onrender.com
# paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
